### ISSUE TITLE
Plugin crashes on connect on macos

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [nyash-qq/galaxy-plugin-poe#7]
Plugin crashes immediately after connecting plugin on a mac.

```
2019-11-15 11:52:59,078 - root - ERROR - Plugin exception
Traceback (most recent call last):
  File "/Applications/GOG Galaxy.app/Contents/Resources/plugin_runner.py", line 35, in <module>
    module = importlib.import_module(filename)
  File "/Applications/GOG Galaxy.app/Contents/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/qa/Library/Application Support/GOG.com/Galaxy/plugins/installed/pathofexile_52d06761-1c23-d725-9720-57ee0b8b14bc/poe_plugin.py", line 12, in <module>
    import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
```

Even if the game is not supported on the system itself a hard crash is never a good thing to show to users.

**Comment by into-the-intraverse** [comment]
Fixed 2d2a11d82c6365e292d2e26a20a362832d2c93a5
